# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wAsistente.ui'
#
# Created: Mon Sep 12 18:44:38 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(472, 311)
        Wizard.setWizardStyle(QtGui.QWizard.AeroStyle)
        Wizard.setOptions(QtGui.QWizard.NoCancelButton)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.label = QtGui.QLabel(self.wizardPage1)
        self.label.setGeometry(QtCore.QRect(10, 50, 131, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.wizardPage1)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 211, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.wizardPage1)
        self.label_3.setGeometry(QtCore.QRect(180, 80, 141, 17))
        self.label_3.setObjectName("label_3")
        self.rbAbrirCatalogo = QtGui.QRadioButton(self.wizardPage1)
        self.rbAbrirCatalogo.setGeometry(QtCore.QRect(190, 120, 211, 22))
        self.rbAbrirCatalogo.setCheckable(True)
        self.rbAbrirCatalogo.setObjectName("rbAbrirCatalogo")
        self.rbCrearCatalogo = QtGui.QRadioButton(self.wizardPage1)
        self.rbCrearCatalogo.setGeometry(QtCore.QRect(190, 150, 191, 22))
        self.rbCrearCatalogo.setObjectName("rbCrearCatalogo")
        Wizard.addPage(self.wizardPage1)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName("wizardPage3")
        self.rbAgregarDefault_2 = QtGui.QRadioButton(self.wizardPage3)
        self.rbAgregarDefault_2.setGeometry(QtCore.QRect(30, 90, 331, 22))
        self.rbAgregarDefault_2.setChecked(True)
        self.rbAgregarDefault_2.setObjectName("rbAgregarDefault_2")
        self.label_6 = QtGui.QLabel(self.wizardPage3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/logo.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.rbAgregarReferencia_2 = QtGui.QRadioButton(self.wizardPage3)
        self.rbAgregarReferencia_2.setGeometry(QtCore.QRect(30, 150, 331, 22))
        self.rbAgregarReferencia_2.setChecked(False)
        self.rbAgregarReferencia_2.setObjectName("rbAgregarReferencia_2")
        self.label_9 = QtGui.QLabel(self.wizardPage3)
        self.label_9.setGeometry(QtCore.QRect(70, 120, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.wizardPage3)
        self.label_10.setGeometry(QtCore.QRect(70, 180, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.lbTitulo_2 = QtGui.QLabel(self.wizardPage3)
        self.lbTitulo_2.setGeometry(QtCore.QRect(90, 10, 221, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbTitulo_2.setFont(font)
        self.lbTitulo_2.setObjectName("lbTitulo_2")
        self.eUbicacion_2 = QtGui.QLineEdit(self.wizardPage3)
        self.eUbicacion_2.setGeometry(QtCore.QRect(50, 230, 371, 21))
        self.eUbicacion_2.setObjectName("eUbicacion_2")
        self.lbOperacion_2 = QtGui.QLabel(self.wizardPage3)
        self.lbOperacion_2.setGeometry(QtCore.QRect(50, 210, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbOperacion_2.setFont(font)
        self.lbOperacion_2.setObjectName("lbOperacion_2")
        self.btExaminar_2 = QtGui.QPushButton(self.wizardPage3)
        self.btExaminar_2.setGeometry(QtCore.QRect(430, 230, 31, 21))
        self.btExaminar_2.setObjectName("btExaminar_2")
        self.eNombreCatalogo = QtGui.QLineEdit(self.wizardPage3)
        self.eNombreCatalogo.setGeometry(QtCore.QRect(250, 50, 171, 21))
        self.eNombreCatalogo.setObjectName("eNombreCatalogo")
        self.lbOperacion_3 = QtGui.QLabel(self.wizardPage3)
        self.lbOperacion_3.setGeometry(QtCore.QRect(100, 50, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbOperacion_3.setFont(font)
        self.lbOperacion_3.setObjectName("lbOperacion_3")
        Wizard.addPage(self.wizardPage3)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.lbTitulo = QtGui.QLabel(self.wizardPage2)
        self.lbTitulo.setGeometry(QtCore.QRect(90, 10, 221, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbTitulo.setFont(font)
        self.lbTitulo.setObjectName("lbTitulo")
        self.label_5 = QtGui.QLabel(self.wizardPage2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.btExaminar = QtGui.QPushButton(self.wizardPage2)
        self.btExaminar.setGeometry(QtCore.QRect(430, 100, 31, 21))
        self.btExaminar.setObjectName("btExaminar")
        self.eUbicacion = QtGui.QLineEdit(self.wizardPage2)
        self.eUbicacion.setGeometry(QtCore.QRect(20, 100, 401, 21))
        self.eUbicacion.setObjectName("eUbicacion")
        self.lbOperacion = QtGui.QLabel(self.wizardPage2)
        self.lbOperacion.setGeometry(QtCore.QRect(20, 80, 151, 17))
        self.lbOperacion.setObjectName("lbOperacion")
        self.rbAgregarDefault = QtGui.QRadioButton(self.wizardPage2)
        self.rbAgregarDefault.setGeometry(QtCore.QRect(30, 130, 331, 22))
        self.rbAgregarDefault.setChecked(True)
        self.rbAgregarDefault.setObjectName("rbAgregarDefault")
        self.label_7 = QtGui.QLabel(self.wizardPage2)
        self.label_7.setGeometry(QtCore.QRect(70, 160, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.rbAgregarReferenciarbAbrirCatalogo_3 = QtGui.QRadioButton(self.wizardPage2)
        self.rbAgregarReferenciarbAbrirCatalogo_3.setGeometry(QtCore.QRect(30, 190, 331, 22))
        self.rbAgregarReferenciarbAbrirCatalogo_3.setChecked(False)
        self.rbAgregarReferenciarbAbrirCatalogo_3.setObjectName("rbAgregarReferenciarbAbrirCatalogo_3")
        self.label_8 = QtGui.QLabel(self.wizardPage2)
        self.label_8.setGeometry(QtCore.QRect(70, 220, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        Wizard.addPage(self.wizardPage2)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(QtGui.QApplication.translate("Wizard", "Bienvenido a Fragmentos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Wizard", "¡Bienvenido a Fragmentos!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Wizard", "¿Que desea hacer?", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAbrirCatalogo.setText(QtGui.QApplication.translate("Wizard", "Abrir un catálogo existente", None, QtGui.QApplication.UnicodeUTF8))
        self.rbCrearCatalogo.setText(QtGui.QApplication.translate("Wizard", "Crear nuevo catálogo", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAgregarDefault_2.setText(QtGui.QApplication.translate("Wizard", "Agregar a carpeta por defecto (Recomendado)", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAgregarReferencia_2.setText(QtGui.QApplication.translate("Wizard", "Agregar ubicación por referencia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Wizard", "Agrega una copia en la carpeta local. Esto permite autocargar todos los catálogos existentes en esta carpeta al inicio del programa.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Wizard", "Solo hará referencia al catálogo desde donde se encuentre seleccionado en el equipo.", None, QtGui.QApplication.UnicodeUTF8))
        self.lbTitulo_2.setText(QtGui.QApplication.translate("Wizard", "Crear nuevo catálogo", None, QtGui.QApplication.UnicodeUTF8))
        self.lbOperacion_2.setText(QtGui.QApplication.translate("Wizard", "Seleccionar ubicación:", None, QtGui.QApplication.UnicodeUTF8))
        self.btExaminar_2.setText(QtGui.QApplication.translate("Wizard", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lbOperacion_3.setText(QtGui.QApplication.translate("Wizard", "Nombre del catálogo:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbTitulo.setText(QtGui.QApplication.translate("Wizard", "Abrir un catálogo existente", None, QtGui.QApplication.UnicodeUTF8))
        self.btExaminar.setText(QtGui.QApplication.translate("Wizard", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lbOperacion.setText(QtGui.QApplication.translate("Wizard", "Seleccionar ubicación:", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAgregarDefault.setText(QtGui.QApplication.translate("Wizard", "Agregar a carpeta por defecto (Recomendado)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Wizard", "Agrega una copia en la carpeta local. Esto permite autocargar todos los catálogos existentes en esta carpeta al inicio del programa.", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAgregarReferenciarbAbrirCatalogo_3.setText(QtGui.QApplication.translate("Wizard", "Agregar ubicación por referencia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Wizard", "Solo hará referencia al catálogo desde donde se encuentre seleccionado en el equipo.", None, QtGui.QApplication.UnicodeUTF8))

import fragmentos_rc
